import { PaperMode } from '@/modules/paper-mode/paper-mode.entity';
import { ExamConfigRequire } from '@/modules/exam-config-require/exam-config-require.entity';
import { PaperModeRequire } from '@/modules/paper-mode-require/paper-mode-require.entity';
import { QuestionConfig } from '@/modules/question-config/question-config.entity';
import { AntiCheatingConfig } from '@/modules/anti-cheating-config/anti-cheating-config.entity';
import { ExamTime } from '@/modules/exam-time/exam-time.entity';
import { AnswerTime } from '@/modules/answer-time/answer-time.entity';
import { TestTimes } from '@/modules/test-times/test-times.entity';
import { GetScoreConfig } from '@/modules/get-score-config/get-score-config.entity';
import { ExamineeFillMessage } from '@/modules/examinee-fill-message/examinee-fill-message.entity';
import { ExamConfig } from '@/modules/exam-config/exam-config.entity';
import { TreePerson } from '@/modules/tree-person/tree-person.entity';
import { GradeConfig } from '@/modules/grade-config/grade-config.entity';
import { GradeConfigRequire } from '@/modules/grade-config-require/grade-config-require.entity';
import { AnswerEquipment } from '@/modules/answer-equipment/answer-equipment.entity';
import { AnswerEquipmentRequire } from '@/modules/answer-equipment-require/answer-equipment-require.entity';
import { PaperExam } from '@/modules/paper-exam/paper-exam.entity';
import { Students } from '@/modules/students/students.entity';
import { ExerciseWay } from '../exercise-way/exercise-way.entity';
export declare class Exercise {
    exerciseId: string;
    exerciseTitle: string;
    exerciseInstructions: string;
    openSignature: number;
    isDelete: number;
    star: number;
    link: string;
    exercisePassword: string;
    isPublish: number;
    exercisePattern: number;
    qrCode: string;
    deleteTime: Date;
    createAt: Date;
    updateAt: Date;
    partStr: string;
    exerciseConfig: ExamConfig;
    paperMode: PaperMode;
    exerciseConfigRequires: ExamConfigRequire[];
    paperModeRequires: PaperModeRequire[];
    questionConfigs: QuestionConfig[];
    antiCheatingConfigs: AntiCheatingConfig[];
    exerciseTimes: ExamTime[];
    answerTimes: AnswerTime[];
    testTimes: TestTimes[];
    getScoreConfig: GetScoreConfig;
    exerciseineeFillMessages: ExamineeFillMessage[];
    exerciseWay: ExerciseWay;
    treePerson: TreePerson;
    gradeConfig: GradeConfig;
    gradeConfigRequires: GradeConfigRequire[];
    answerEquipment: AnswerEquipment;
    answerEquipmentRequires: AnswerEquipmentRequire[];
    paperExam: PaperExam;
    students: Students[];
    questionConfiges: QuestionConfig[];
}
